export const list = [
  {
    id: 20,
    list: {
      title: 'Best Books Ever',
      description:
        "The best books ever, as voted on by the general Goodreads community. Note to librarians: do not edit this list's description.",
      booksAmount: 56,
      items: [
        {
          id: 2767052,
          url: 'https://www.goodreads.com/book/show/2767052-the-hunger-games',
          title: 'The Hunger Games (The Hunger Games, #1)',
          author: 'Suzanne Collins',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722975i/2767052._SY75_.jpg',
          rating: 4.32,
          ratings: 7045579,
          rankingPosition: 1,
        },
        {
          id: 2,
          url: 'https://www.goodreads.com/book/show/2.Harry_Potter_and_the_Order_of_the_Phoenix',
          title: 'Harry Potter and the Order of the Phoenix (Harry Potter, #5)',
          author: 'J.K. Rowling',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265i/2._SX50_.jpg',
          rating: 4.5,
          ratings: 2803310,
          rankingPosition: 2,
        },
        {
          id: 2657,
          url: 'https://www.goodreads.com/book/show/2657.To_Kill_a_Mockingbird',
          title: 'To Kill a Mockingbird',
          author: 'Harper Lee',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657._SY75_.jpg',
          rating: 4.27,
          ratings: 5016864,
          rankingPosition: 3,
        },
        {
          id: 1885,
          url: 'https://www.goodreads.com/book/show/1885.Pride_and_Prejudice',
          title: 'Pride and Prejudice',
          author: 'Jane Austen',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885._SY75_.jpg',
          rating: 4.27,
          ratings: 3400452,
          rankingPosition: 4,
        },
        {
          id: 41865,
          url: 'https://www.goodreads.com/book/show/41865.Twilight',
          title: 'Twilight (The Twilight Saga, #1)',
          author: 'Stephenie Meyer',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1361039443i/41865._SY75_.jpg',
          rating: 3.62,
          ratings: 5482551,
          rankingPosition: 5,
        },
        {
          id: 19063,
          url: 'https://www.goodreads.com/book/show/19063.The_Book_Thief',
          title: 'The Book Thief',
          author: 'Markus Zusak',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1522157426i/19063._SY75_.jpg',
          rating: 4.38,
          ratings: 2068369,
          rankingPosition: 6,
        },
        {
          id: 170448,
          url: 'https://www.goodreads.com/book/show/170448.Animal_Farm',
          title: 'Animal Farm',
          author: 'George Orwell',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1325861570i/170448._SY75_.jpg',
          rating: 3.97,
          ratings: 3099185,
          rankingPosition: 7,
        },
        {
          id: 11127,
          url: 'https://www.goodreads.com/book/show/11127.The_Chronicles_of_Narnia',
          title: 'The Chronicles of Narnia (Chronicles of Narnia, #1-7)',
          author: 'C.S. Lewis',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1449868701i/11127._SY75_.jpg',
          rating: 4.25,
          ratings: 573935,
          rankingPosition: 8,
        },
        {
          id: 30,
          url: 'https://www.goodreads.com/book/show/30.J_R_R_Tolkien_4_Book_Boxed_Set',
          title:
            'J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings',
          author: 'J.R.R. Tolkien',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1346072396i/30._SX50_.jpg',
          rating: 4.6,
          ratings: 119463,
          rankingPosition: 9,
        },
        {
          id: 11870085,
          url: 'https://www.goodreads.com/book/show/11870085-the-fault-in-our-stars',
          title: 'The Fault in Our Stars',
          author: 'John Green',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1632632557i/11870085._SX50_.jpg',
          rating: 4.18,
          ratings: 4057586,
          rankingPosition: 10,
        },
        {
          id: 18405,
          url: 'https://www.goodreads.com/book/show/18405.Gone_with_the_Wind',
          title: 'Gone with the Wind',
          author: 'Margaret Mitchell',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1551144577i/18405._SY75_.jpg',
          rating: 4.3,
          ratings: 1134910,
          rankingPosition: 11,
        },
        {
          id: 386162,
          url: 'https://www.goodreads.com/book/show/386162.The_Hitchhiker_s_Guide_to_the_Galaxy',
          title:
            "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)",
          author: 'Douglas Adams',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1559986152i/386162._SX50_.jpg',
          rating: 4.22,
          ratings: 1587322,
          rankingPosition: 12,
        },
        {
          id: 370493,
          url: 'https://www.goodreads.com/book/show/370493.The_Giving_Tree',
          title: 'The Giving Tree',
          author: 'Shel Silverstein',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1174210942i/370493._SX50_.jpg',
          rating: 4.37,
          ratings: 987466,
          rankingPosition: 13,
        },
        {
          id: 6185,
          url: 'https://www.goodreads.com/book/show/6185.Wuthering_Heights',
          title: 'Wuthering Heights',
          author: 'Emily Brontë',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630501681i/6185._SY75_.jpg',
          rating: 3.87,
          ratings: 1488548,
          rankingPosition: 14,
        },
        {
          id: 5297,
          url: 'https://www.goodreads.com/book/show/5297.The_Picture_of_Dorian_Gray',
          title: 'The Picture of Dorian Gray',
          author: 'Oscar Wilde',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546103428i/5297._SY75_.jpg',
          rating: 4.1,
          ratings: 1121098,
          rankingPosition: 15,
        },
        {
          id: 968,
          url: 'https://www.goodreads.com/book/show/968.The_Da_Vinci_Code',
          title: 'The Da Vinci Code (Robert Langdon, #2)',
          author: 'Dan Brown',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1579621267i/968._SY75_.jpg',
          rating: 3.88,
          ratings: 2093167,
          rankingPosition: 16,
        },
        {
          id: 10210,
          url: 'https://www.goodreads.com/book/show/10210.Jane_Eyre',
          title: 'Jane Eyre',
          author: 'Charlotte Brontë',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1557343311i/10210._SY75_.jpg',
          rating: 4.13,
          ratings: 1783205,
          rankingPosition: 17,
        },
        {
          id: 929,
          url: 'https://www.goodreads.com/book/show/929.Memoirs_of_a_Geisha',
          title: 'Memoirs of a Geisha',
          author: 'Arthur Golden',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1409595968i/929._SY75_.jpg',
          rating: 4.13,
          ratings: 1820669,
          rankingPosition: 18,
        },
        {
          id: 24213,
          url: 'https://www.goodreads.com/book/show/24213.Alice_s_Adventures_in_Wonderland_Through_the_Looking_Glass',
          title: "Alice's Adventures in Wonderland / Through the Looking-Glass",
          author: 'Lewis Carroll',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630487234i/24213._SX50_.jpg',
          rating: 4.06,
          ratings: 500129,
          rankingPosition: 19,
        },
        {
          id: 24280,
          url: 'https://www.goodreads.com/book/show/24280.Les_Mis_rables',
          title: 'Les Misérables',
          author: 'Victor Hugo',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1411852091i/24280._SY75_.jpg',
          rating: 4.18,
          ratings: 726788,
          rankingPosition: 20,
        },
        {
          id: 22628,
          url: 'https://www.goodreads.com/book/show/22628.The_Perks_of_Being_a_Wallflower',
          title: 'The Perks of Being a Wallflower',
          author: 'Stephen Chbosky',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1520093244i/22628._SY75_.jpg',
          rating: 4.21,
          ratings: 1416140,
          rankingPosition: 21,
        },
        {
          id: 13079982,
          url: 'https://www.goodreads.com/book/show/13079982-fahrenheit-451',
          title: 'Fahrenheit 451',
          author: 'Ray Bradbury',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1383718290i/13079982._SY75_.jpg',
          rating: 3.98,
          ratings: 1915559,
          rankingPosition: 22,
        },
        {
          id: 13335037,
          url: 'https://www.goodreads.com/book/show/13335037-divergent',
          title: 'Divergent (Divergent, #1)',
          author: 'Veronica Roth',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1618526890i/13335037._SY75_.jpg',
          rating: 4.17,
          ratings: 3269942,
          rankingPosition: 23,
        },
        {
          id: 3,
          url: 'https://www.goodreads.com/book/show/3.Harry_Potter_and_the_Sorcerer_s_Stone',
          title: "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",
          author: 'J.K. Rowling',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474154022i/3._SY75_.jpg',
          rating: 4.47,
          ratings: 8014012,
          rankingPosition: 24,
        },
        {
          id: 4671,
          url: 'https://www.goodreads.com/book/show/4671.The_Great_Gatsby',
          title: 'The Great Gatsby',
          author: 'F. Scott Fitzgerald',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1490528560i/4671._SY75_.jpg',
          rating: 3.93,
          ratings: 4209639,
          rankingPosition: 25,
        },
        {
          id: 18144590,
          url: 'https://www.goodreads.com/book/show/18144590-the-alchemist',
          title: 'The Alchemist',
          author: 'Paulo Coelho',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1466865542i/18144590._SY75_.jpg',
          rating: 3.89,
          ratings: 2396375,
          rankingPosition: 26,
        },
        {
          id: 7624,
          url: 'https://www.goodreads.com/book/show/7624.Lord_of_the_Flies',
          title: 'Lord of the Flies',
          author: 'William Golding',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327869409i/7624._SY75_.jpg',
          rating: 3.69,
          ratings: 2481628,
          rankingPosition: 27,
        },
        {
          id: 7144,
          url: 'https://www.goodreads.com/book/show/7144.Crime_and_Punishment',
          title: 'Crime and Punishment',
          author: 'Fyodor Dostoevsky',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1382846449i/7144._SY75_.jpg',
          rating: 4.23,
          ratings: 713159,
          rankingPosition: 28,
        },
        {
          id: 18135,
          url: 'https://www.goodreads.com/book/show/18135.Romeo_and_Juliet',
          title: 'Romeo and Juliet',
          author: 'William Shakespeare',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630631323i/18135._SY75_.jpg',
          rating: 3.75,
          ratings: 2230889,
          rankingPosition: 29,
        },
        {
          id: 157993,
          url: 'https://www.goodreads.com/book/show/157993.The_Little_Prince',
          title: 'The Little Prince',
          author: 'Antoine de Saint-Exupéry',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1367545443i/157993._SY75_.jpg',
          rating: 4.31,
          ratings: 1611998,
          rankingPosition: 30,
        },
        {
          id: 256683,
          url: 'https://www.goodreads.com/book/show/256683.City_of_Bones',
          title: 'City of Bones (The Mortal Instruments, #1)',
          author: 'Cassandra Clare',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1432730315i/256683._SY75_.jpg',
          rating: 4.08,
          ratings: 1775709,
          rankingPosition: 31,
        },
        {
          id: 8127,
          url: 'https://www.goodreads.com/book/show/8127.Anne_of_Green_Gables',
          title: 'Anne of Green Gables (Anne of Green Gables, #1)',
          author: 'L.M. Montgomery',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1615094578i/8127._SY75_.jpg',
          rating: 4.26,
          ratings: 821036,
          rankingPosition: 32,
        },
        {
          id: 4667024,
          url: 'https://www.goodreads.com/book/show/4667024-the-help',
          title: 'The Help',
          author: 'Kathryn Stockett',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1622355533i/4667024._SY75_.jpg',
          rating: 4.46,
          ratings: 2361706,
          rankingPosition: 33,
        },
        {
          id: 375802,
          url: 'https://www.goodreads.com/book/show/375802.Ender_s_Game',
          title: "Ender's Game (Ender's Saga, #1)",
          author: 'Orson Scott Card',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1408303130i/375802._SY75_.jpg',
          rating: 4.3,
          ratings: 1228250,
          rankingPosition: 34,
        },
        {
          id: 28187,
          url: 'https://www.goodreads.com/book/show/28187.The_Lightning_Thief',
          title: 'The Lightning Thief (Percy Jackson and the Olympians, #1)',
          author: 'Rick Riordan',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1400602609i/28187._SY75_.jpg',
          rating: 4.27,
          ratings: 2296592,
          rankingPosition: 35,
        },
        {
          id: 24178,
          url: 'https://www.goodreads.com/book/show/24178.Charlotte_s_Web',
          title: "Charlotte's Web",
          author: 'E.B. White',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1628267712i/24178._SY75_.jpg',
          rating: 4.18,
          ratings: 1566085,
          rankingPosition: 36,
        },
        {
          id: 890,
          url: 'https://www.goodreads.com/book/show/890.Of_Mice_and_Men',
          title: 'Of Mice and Men',
          author: 'John Steinbeck',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1511302904i/890._SX50_.jpg',
          rating: 3.88,
          ratings: 2126518,
          rankingPosition: 37,
        },
        {
          id: 17245,
          url: 'https://www.goodreads.com/book/show/17245.Dracula',
          title: 'Dracula',
          author: 'Bram Stoker',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1387151694i/17245._SY75_.jpg',
          rating: null,
          ratings: 1047087,
          rankingPosition: 38,
        },
        {
          id: 18619684,
          url: 'https://www.goodreads.com/book/show/18619684-the-time-traveler-s-wife',
          title: "The Time Traveler's Wife",
          author: 'Audrey Niffenegger',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1380660571i/18619684._SX50_.jpg',
          rating: 3.98,
          ratings: 1661217,
          rankingPosition: 39,
        },
        {
          id: 5129,
          url: 'https://www.goodreads.com/book/show/5129.Brave_New_World',
          title: 'Brave New World',
          author: 'Aldous Huxley',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1575509280i/5129._SY75_.jpg',
          rating: 3.99,
          ratings: 1587530,
          rankingPosition: 40,
        },
        {
          id: 320,
          url: 'https://www.goodreads.com/book/show/320.One_Hundred_Years_of_Solitude',
          title: 'One Hundred Years of Solitude',
          author: 'Gabriel García Márquez',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327881361i/320._SX50_.jpg',
          rating: 4.09,
          ratings: 825866,
          rankingPosition: 41,
        },
        {
          id: 5107,
          url: 'https://www.goodreads.com/book/show/5107.The_Catcher_in_the_Rye',
          title: 'The Catcher in the Rye',
          author: 'J.D. Salinger',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107._SY75_.jpg',
          rating: 3.81,
          ratings: 2992251,
          rankingPosition: 42,
        },
        {
          id: 21787,
          url: 'https://www.goodreads.com/book/show/21787.The_Princess_Bride',
          title: 'The Princess Bride',
          author: 'William Goldman',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327903636i/21787._SY75_.jpg',
          rating: 4.25,
          ratings: 834154,
          rankingPosition: 43,
        },
        {
          id: 128029,
          url: 'https://www.goodreads.com/book/show/128029.A_Thousand_Splendid_Suns',
          title: 'A Thousand Splendid Suns',
          author: 'Khaled Hosseini',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1345958969i/128029._SY75_.jpg',
          rating: 4.39,
          ratings: 1274194,
          rankingPosition: 44,
        },
        {
          id: 2998,
          url: 'https://www.goodreads.com/book/show/2998.The_Secret_Garden',
          title: 'The Secret Garden',
          author: 'Frances Hodgson Burnett',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327873635i/2998._SY75_.jpg',
          rating: 4.13,
          ratings: 995281,
          rankingPosition: 45,
        },
        {
          id: 13496,
          url: 'https://www.goodreads.com/book/show/13496.A_Game_of_Thrones',
          title: 'A Game of Thrones (A Song of Ice and Fire, #1)',
          author: 'George R.R. Martin',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1562726234i/13496._SY75_.jpg',
          rating: 4.44,
          ratings: 2168432,
          rankingPosition: 46,
        },
        {
          id: 33574273,
          url: 'https://www.goodreads.com/book/show/33574273-a-wrinkle-in-time',
          title: 'A Wrinkle in Time (Time Quintet, #1)',
          author: "Madeleine L'Engle",
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1507963312i/33574273._SX50_.jpg',
          rating: 3.99,
          ratings: 1111881,
          rankingPosition: 47,
        },
        {
          id: 231804,
          url: 'https://www.goodreads.com/book/show/231804.The_Outsiders',
          title: 'The Outsiders',
          author: 'S.E. Hinton',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1442129426i/231804._SY75_.jpg',
          rating: 4.1,
          ratings: 1063098,
          rankingPosition: 48,
        },
        {
          id: 2956,
          url: 'https://www.goodreads.com/book/show/2956.The_Adventures_of_Huckleberry_Finn',
          title: 'The Adventures of Huckleberry Finn',
          author: 'Mark Twain',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546096879i/2956._SX50_.jpg',
          rating: 3.82,
          ratings: 1199441,
          rankingPosition: 49,
        },
        {
          id: 12232938,
          url: 'https://www.goodreads.com/book/show/12232938-the-lovely-bones',
          title: 'The Lovely Bones',
          author: 'Alice Sebold',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1457810586i/12232938._SY75_.jpg',
          rating: 3.83,
          ratings: 2147234,
          rankingPosition: 50,
        },
        {
          id: 1381,
          url: 'https://www.goodreads.com/book/show/1381.The_Odyssey',
          title: 'The Odyssey',
          author: 'Homer',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1390173285i/1381._SY75_.jpg',
          rating: 3.78,
          ratings: 928558,
          rankingPosition: 51,
        },
        {
          id: 19543,
          url: 'https://www.goodreads.com/book/show/19543.Where_the_Wild_Things_Are',
          title: 'Where the Wild Things Are',
          author: 'Maurice Sendak',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1384434560i/19543._SX50_.jpg',
          rating: 4.22,
          ratings: 892713,
          rankingPosition: 52,
        },
        {
          id: 23772,
          url: 'https://www.goodreads.com/book/show/23772.Green_Eggs_and_Ham',
          title: 'Green Eggs and Ham',
          author: 'Dr. Seuss',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1468680100i/23772._SX50_.jpg',
          rating: 4.29,
          ratings: 682597,
          rankingPosition: 53,
        },
        {
          id: 4214,
          url: 'https://www.goodreads.com/book/show/4214.Life_of_Pi',
          title: 'Life of Pi',
          author: 'Yann Martel',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631251689i/4214._SY75_.jpg',
          rating: 3.92,
          ratings: 1442363,
          rankingPosition: 54,
        },
        {
          id: 1953,
          url: 'https://www.goodreads.com/book/show/1953.A_Tale_of_Two_Cities',
          title: 'A Tale of Two Cities',
          author: 'Charles Dickens',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1344922523i/1953._SY75_.jpg',
          rating: 3.86,
          ratings: 860228,
          rankingPosition: 55,
        },
        {
          id: 43641,
          url: 'https://www.goodreads.com/book/show/43641.Water_for_Elephants',
          title: 'Water for Elephants',
          author: 'Sara Gruen',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1494428973i/43641._SY75_.jpg',
          rating: 4.09,
          ratings: 1470569,
          rankingPosition: 56,
        },
        {
          id: 77203,
          url: 'https://www.goodreads.com/book/show/77203.The_Kite_Runner',
          title: 'The Kite Runner',
          author: 'Khaled Hosseini',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1579036753i/77203._SY75_.jpg',
          rating: 4.32,
          ratings: 2661403,
          rankingPosition: 57,
        },
        {
          id: 7604,
          url: 'https://www.goodreads.com/book/show/7604.Lolita',
          title: 'Lolita',
          author: 'Vladimir Nabokov',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1377756377i/7604._SY75_.jpg',
          rating: 3.88,
          ratings: 722749,
          rankingPosition: 58,
        },
        {
          id: 35031085,
          url: 'https://www.goodreads.com/book/show/35031085-frankenstein',
          title: 'Frankenstein: The 1818 Text',
          author: 'Mary Wollstonecraft Shelley',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631088473i/35031085._SY75_.jpg',
          rating: 3.83,
          ratings: 1290528,
          rankingPosition: 59,
        },
        {
          id: 38447,
          url: 'https://www.goodreads.com/book/show/38447.The_Handmaid_s_Tale',
          title: "The Handmaid's Tale (The Handmaid's Tale, #1)",
          author: 'Margaret Atwood',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1578028274i/38447._SY75_.jpg',
          rating: 4.12,
          ratings: 1656840,
          rankingPosition: 60,
        },
        {
          id: 4981,
          url: 'https://www.goodreads.com/book/show/4981.Slaughterhouse_Five',
          title: 'Slaughterhouse-Five',
          author: 'Kurt Vonnegut Jr.',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1606208827i/4981._SY75_.jpg',
          rating: 4.08,
          ratings: 1216733,
          rankingPosition: 61,
        },
        {
          id: 3636,
          url: 'https://www.goodreads.com/book/show/3636.The_Giver',
          title: 'The Giver (The Giver, #1)',
          author: 'Lois Lowry',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1342493368i/3636._SY75_.jpg',
          rating: 4.13,
          ratings: 2007288,
          rankingPosition: 62,
        },
        {
          id: 44767458,
          url: 'https://www.goodreads.com/book/show/44767458-dune',
          title: 'Dune (Dune, #1)',
          author: 'Frank Herbert',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458._SY75_.jpg',
          rating: 4.24,
          ratings: 960697,
          rankingPosition: 63,
        },
        {
          id: 1934,
          url: 'https://www.goodreads.com/book/show/1934.Little_Women',
          title: 'Little Women',
          author: 'Louisa May Alcott',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1562690475i/1934._SY75_.jpg',
          rating: 4.11,
          ratings: 1851578,
          rankingPosition: 64,
        },
        {
          id: 136251,
          url: 'https://www.goodreads.com/book/show/136251.Harry_Potter_and_the_Deathly_Hallows',
          title: 'Harry Potter and the Deathly Hallows (Harry Potter, #7)',
          author: 'J.K. Rowling',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1474171184i/136251._SY75_.jpg',
          rating: 4.61,
          ratings: 3114323,
          rankingPosition: 65,
        },
        {
          id: 168668,
          url: 'https://www.goodreads.com/book/show/168668.Catch_22',
          title: 'Catch-22',
          author: 'Joseph Heller',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1463157317i/168668._SY75_.jpg',
          rating: 3.98,
          ratings: 767117,
          rankingPosition: 66,
        },
        {
          id: 149267,
          url: 'https://www.goodreads.com/book/show/149267.The_Stand',
          title: 'The Stand',
          author: 'Stephen King',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1213131305i/149267._SX50_.jpg',
          rating: 4.33,
          ratings: 679209,
          rankingPosition: 67,
        },
        {
          id: 5043,
          url: 'https://www.goodreads.com/book/show/5043.The_Pillars_of_the_Earth',
          title: 'The Pillars of the Earth (Kingsbridge, #1)',
          author: 'Ken Follett',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1576956100i/5043._SY75_.jpg',
          rating: 4.32,
          ratings: 694729,
          rankingPosition: 68,
        },
        {
          id: 3590,
          url: 'https://www.goodreads.com/book/show/3590.The_Adventures_of_Sherlock_Holmes',
          title: 'The Adventures of Sherlock Holmes (Sherlock Holmes, #3)',
          author: 'Arthur Conan Doyle',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1164045516i/3590._SY75_.jpg',
          rating: 4.29,
          ratings: 268632,
          rankingPosition: 69,
        },
        {
          id: 76620,
          url: 'https://www.goodreads.com/book/show/76620.Watership_Down',
          title: 'Watership Down (Watership Down, #1)',
          author: 'Richard  Adams',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1405136931i/76620._SY75_.jpg',
          rating: 4.06,
          ratings: 455939,
          rankingPosition: 70,
        },
        {
          id: 2623,
          url: 'https://www.goodreads.com/book/show/2623.Great_Expectations',
          title: 'Great Expectations',
          author: 'Charles Dickens',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631687432i/2623._SY75_.jpg',
          rating: 3.78,
          ratings: 705488,
          rankingPosition: 71,
        },
        {
          id: 6514,
          url: 'https://www.goodreads.com/book/show/6514.The_Bell_Jar',
          title: 'The Bell Jar',
          author: 'Sylvia Plath',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1554582218i/6514._SY75_.jpg',
          rating: 4.02,
          ratings: 679880,
          rankingPosition: 72,
        },
        {
          id: 39988,
          url: 'https://www.goodreads.com/book/show/39988.Matilda',
          title: 'Matilda',
          author: 'Roald Dahl',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1388793265i/39988._SY75_.jpg',
          rating: 4.32,
          ratings: 752782,
          rankingPosition: 73,
        },
        {
          id: 15823480,
          url: 'https://www.goodreads.com/book/show/15823480-anna-karenina',
          title: 'Anna Karenina',
          author: 'Leo Tolstoy',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1601352433i/15823480._SX50_.jpg',
          rating: 4.06,
          ratings: 729277,
          rankingPosition: 74,
        },
        {
          id: 3263607,
          url: 'https://www.goodreads.com/book/show/3263607-the-fellowship-of-the-ring',
          title: 'The Fellowship of the Ring (The Lord of the Rings, #1)',
          author: 'J.R.R. Tolkien',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1486871542i/3263607._SY75_.jpg',
          rating: 4.37,
          ratings: 2520254,
          rankingPosition: 75,
        },
        {
          id: 332613,
          url: 'https://www.goodreads.com/book/show/332613.One_Flew_Over_the_Cuckoo_s_Nest',
          title: "One Flew Over the Cuckoo's Nest",
          author: 'Ken Kesey',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1516211014i/332613._SX50_.jpg',
          rating: 4.19,
          ratings: 674369,
          rankingPosition: 76,
        },
        {
          id: 10964,
          url: 'https://www.goodreads.com/book/show/10964.Outlander',
          title: 'Outlander (Outlander, #1)',
          author: 'Diana Gabaldon',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1529065012i/10964._SY75_.jpg',
          rating: 4.23,
          ratings: 912943,
          rankingPosition: 77,
        },
        {
          id: 2429135,
          url: 'https://www.goodreads.com/book/show/2429135.The_Girl_with_the_Dragon_Tattoo',
          title: 'The Girl with the Dragon Tattoo (Millennium, #1)',
          author: 'Stieg Larsson',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327868566i/2429135._SX50_.jpg',
          rating: 4.15,
          ratings: 2834430,
          rankingPosition: 78,
        },
        {
          id: 17899948,
          url: 'https://www.goodreads.com/book/show/17899948-rebecca',
          title: 'Rebecca',
          author: 'Daphne du Maurier',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1386605169i/17899948._SX50_.jpg',
          rating: 4.23,
          ratings: 524661,
          rankingPosition: 79,
        },
        {
          id: 10917,
          url: 'https://www.goodreads.com/book/show/10917.My_Sister_s_Keeper',
          title: "My Sister's Keeper",
          author: 'Jodi Picoult',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1369504683i/10917._SY75_.jpg',
          rating: 4.08,
          ratings: 1114116,
          rankingPosition: 80,
        },
        {
          id: 52892857,
          url: 'https://www.goodreads.com/book/show/52892857-the-color-purple',
          title: 'The Color Purple',
          author: 'Alice Walker',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1572261616l/52892857._SX50_SY75_.jpg',
          rating: 4.24,
          ratings: 574423,
          rankingPosition: 81,
        },
        {
          id: 5,
          url: 'https://www.goodreads.com/book/show/5.Harry_Potter_and_the_Prisoner_of_Azkaban',
          title: 'Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)',
          author: 'J.K. Rowling',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630547330i/5._SY75_.jpg',
          rating: 4.57,
          ratings: 3228744,
          rankingPosition: 82,
        },
        {
          id: 14891,
          url: 'https://www.goodreads.com/book/show/14891.A_Tree_Grows_in_Brooklyn',
          title: 'A Tree Grows in Brooklyn',
          author: 'Betty  Smith',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327883484i/14891._SY75_.jpg',
          rating: 4.28,
          ratings: 414008,
          rankingPosition: 83,
        },
        {
          id: 4934,
          url: 'https://www.goodreads.com/book/show/4934.The_Brothers_Karamazov',
          title: 'The Brothers Karamazov',
          author: 'Fyodor Dostoevsky',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1427728126i/4934._SX50_.jpg',
          rating: 4.32,
          ratings: 271570,
          rankingPosition: 84,
        },
        {
          id: 41817486,
          url: 'https://www.goodreads.com/book/show/41817486-a-clockwork-orange',
          title: 'A Clockwork Orange',
          author: 'Anthony Burgess',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1549260060i/41817486._SX50_.jpg',
          rating: 3.99,
          ratings: 653492,
          rankingPosition: 85,
        },
        {
          id: 6288,
          url: 'https://www.goodreads.com/book/show/6288.The_Road',
          title: 'The Road',
          author: 'Cormac McCarthy',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1600241424i/6288._SY75_.jpg',
          rating: 3.97,
          ratings: 782488,
          rankingPosition: 86,
        },
        {
          id: 40961427,
          url: 'https://www.goodreads.com/book/show/40961427-1984',
          title: '1984',
          author: 'George Orwell',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1532714506i/40961427._SX50_.jpg',
          rating: 4.19,
          ratings: 3602057,
          rankingPosition: 87,
        },
        {
          id: 252577,
          url: 'https://www.goodreads.com/book/show/252577.Angela_s_Ashes',
          title: "Angela's Ashes (Frank McCourt, #1)",
          author: 'Frank McCourt',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348317139i/252577._SY75_.jpg',
          rating: 4.12,
          ratings: 577870,
          rankingPosition: 88,
        },
        {
          id: 345627,
          url: 'https://www.goodreads.com/book/show/345627.Vampire_Academy',
          title: 'Vampire Academy (Vampire Academy, #1)',
          author: 'Richelle Mead',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1361098973i/345627._SY75_.jpg',
          rating: 4.11,
          ratings: 602100,
          rankingPosition: 89,
        },
        {
          id: 52036,
          url: 'https://www.goodreads.com/book/show/52036.Siddhartha',
          title: 'Siddhartha',
          author: 'Hermann Hesse',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1629378189i/52036._SY75_.jpg',
          rating: 4.04,
          ratings: 646194,
          rankingPosition: 90,
        },
        {
          id: 7244,
          url: 'https://www.goodreads.com/book/show/7244.The_Poisonwood_Bible',
          title: 'The Poisonwood Bible',
          author: 'Barbara Kingsolver',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1412242487i/7244._SY75_.jpg',
          rating: 4.07,
          ratings: 688879,
          rankingPosition: 91,
        },
        {
          id: 119322,
          url: 'https://www.goodreads.com/book/show/119322.The_Golden_Compass',
          title: 'The Golden Compass (His Dark Materials, #1)',
          author: 'Philip Pullman',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1505766203i/119322._SX50_.jpg',
          rating: null,
          ratings: 1383328,
          rankingPosition: 92,
        },
        {
          id: 3836,
          url: 'https://www.goodreads.com/book/show/3836.Don_Quixote',
          title: 'Don Quixote',
          author: 'Miguel de Cervantes Saavedra',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546112331i/3836._SX50_.jpg',
          rating: 3.88,
          ratings: 232914,
          rankingPosition: 93,
        },
        {
          id: 662,
          url: 'https://www.goodreads.com/book/show/662.Atlas_Shrugged',
          title: 'Atlas Shrugged',
          author: 'Ayn Rand',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1405868167i/662._SY75_.jpg',
          rating: 3.69,
          ratings: 370016,
          rankingPosition: 94,
        },
        {
          id: 2165,
          url: 'https://www.goodreads.com/book/show/2165.The_Old_Man_and_the_Sea',
          title: 'The Old Man and the Sea',
          author: 'Ernest Hemingway',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1630572642i/2165._SY75_.jpg',
          rating: 3.79,
          ratings: 931638,
          rankingPosition: 95,
        },
        {
          id: 33648131,
          url: 'https://www.goodreads.com/book/show/33648131-the-notebook',
          title: 'The Notebook (The Notebook, #1)',
          author: 'Nicholas Sparks',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1483183484i/33648131._SY75_.jpg',
          rating: 4.12,
          ratings: 1443357,
          rankingPosition: 96,
        },
        {
          id: 99107,
          url: 'https://www.goodreads.com/book/show/99107.Winnie_the_Pooh',
          title: 'Winnie-the-Pooh (Winnie-the-Pooh, #1)',
          author: 'A.A. Milne',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1298440130i/99107._SY75_.jpg',
          rating: 4.31,
          ratings: 298800,
          rankingPosition: 97,
        },
        {
          id: 23919,
          url: 'https://www.goodreads.com/book/show/23919.The_Complete_Stories_and_Poems',
          title: 'The Complete Stories and Poems',
          author: 'Edgar Allan Poe',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327942676i/23919._SY75_.jpg',
          rating: 4.37,
          ratings: 237757,
          rankingPosition: 98,
        },
        {
          id: 43763,
          url: 'https://www.goodreads.com/book/show/43763.Interview_with_the_Vampire',
          title: 'Interview with the Vampire (The Vampire Chronicles, #1)',
          author: 'Anne Rice',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1380631642i/43763._SY75_.jpg',
          rating: null,
          ratings: 521931,
          rankingPosition: 99,
        },
        {
          id: 4473,
          url: 'https://www.goodreads.com/book/show/4473.A_Prayer_for_Owen_Meany',
          title: 'A Prayer for Owen Meany',
          author: 'John Irving',
          imageURL:
            'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1260470010i/4473._SY75_.jpg',
          rating: 4.23,
          ratings: 297536,
          rankingPosition: 100,
        },
      ],
    },
  },
]
